#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100
# FizzBuzz for multiple of 3 and 5
# Fizz for multiple of 3
# Buzz for multiple of 5

for ((i = 1; i <=100; i++))
do
	if ((i%3==0)) && ((i%5==0))
	then
		echo "FizzBuzz"
	elif ((i%3==0))
	then
		echo "Fizz"
	elif ((i%5==0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
