#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20

i=1
while ((i <= 20))
do
	echo $i
	if ((i == 4))
	then
		echo "bad luck from China"
	fi
	if ((i == 9))
	then
		echo "bad luck from Japan"
	fi
	if ((i == 17))
	then
		echo "bad luck from Italy"
	fi
	((i++))
done
